sudo: false
language: ruby
script: "bundle exec rake ci"
env:
  - TRAVIS=true
rvm:
  - '2.0'
  - '2.1'
  - rbx-2
matrix:
  allow_failures:
    - rvm: rbx-2 # travis does not maintain rbx setup correctly
notifications:
  irc:
    channels:
      - irc.freenode.org#mutant
    on_success: never
    on_failure: change
