language: ruby
script: 'bundle exec rake ci'
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - rbx-19mode
matrix:
  allow_failures:
    # We'll see what happens
    - rvm: ruby-head
    - rvm: 2.0.0
notifications:
  irc:
    channels:
      - irc.freenode.org#datamapper
    on_success: never
    on_failure: change
