before_install:
  - gem install mbj-inflector
language: ruby
script: 'bundle exec rake spec'
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx-19mode
matrix:
  allow_failures:
    # No mutators for 1.8 specifc AST nodes
    - rvm: rbx-18mode  
    - rvm: 1.8.7
notifications:
  email:
    - mbj@seonic.net
