language: ruby
script: 'bundle exec rake spec'
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - rbx-19mode
matrix:
  allow_failures:
    # No mutators for 1.8 specifc AST nodes
    - rvm: rbx-18mode
    - rvm: 1.8.7
    # We'll see what happens
    - rvm: ruby-head
    - rvm: 2.0.0
notifications:
  email:
    - mbj@seonic.net
