before_install:
  - gem install bundler
language: ruby
script: 'bundle exec rake spec'
rvm:
  # - 1.8.7 disabled while spiking mutations
  - rbx-18mode
  - rbx-19mode
notifications:
  email:
    - mbj@seonic.net
