name: mutant
namespace: Mutant
zombify: true
expect_coverage: 61.83
ignore_subjects:
# Mutation causes infinite runtime
- Mutant::Runner.lookup
# Suboptimal test selection stragegy (will be fixed soon) causes timeouts on CI
- Mutant::Zombifier*
- Mutant::Reporter*
- Mutant::CLI*
- Mutant.singleton_subclass_instance
# Executing this has undefined behavior with the zombifier
- Mutant.zombify
