---
Attribute:
  enabled: false
  exclude: []
BooleanParameter:
  enabled: true
  exclude: []
ClassVariable:
  enabled: true
  exclude: []
ControlParameter:
  enabled: true
  exclude:
  - Mutant::Expression#match_length
DataClump:
  enabled: true
  exclude: []
  max_copies: 2
  min_clump_size: 2
DuplicateMethodCall:
  enabled: false
  exclude: []
  max_calls: 1
  allow_calls: []
FeatureEnvy:
  enabled: false
# Buggy smell detector
IrresponsibleModule:
  enabled: false
  exclude: []
LongParameterList:
  enabled: true
  exclude:
  - Mutant::Matcher::Method::Instance#self.build
  max_params: 2
LongYieldList:
  enabled: true
  exclude: []
  max_params: 2
NestedIterators:
  enabled: true
  exclude:
  - Mutant#self.singleton_subclass_instance
  - Mutant::CLI#parse
  - Mutant::Isolation::Fork#self.call
  - Mutant::Mutator::Util::Array::Element#dispatch
  - Mutant::Mutator::Node::Resbody#mutate_captures
  - Mutant::Mutator::Node::Arguments#emit_argument_mutations
  - Mutant::RequireHighjack#infect
  - Mutant::RequireHighjack#disinfect
  - Mutant::Selector::Expression#call
  - Mutant::Parallel::Master#run
  - Parser::Lexer#self.new
  max_allowed_nesting: 1
  ignore_iterators: []
NilCheck:
  enabled: false
RepeatedConditional:
  enabled: true
  exclude:
  - Mutant::Mutator
  - Mutant::Meta::Example::DSL
  max_ifs: 1
TooManyInstanceVariables:
  enabled: true
  exclude:
  - Mutant::Mutator # 4 vars
  - Mutant::Parallel::Master # 4 vars
  max_instance_variables: 3
TooManyMethods:
  enabled: true
  exclude:
  - Mutant::CLI
  - Mutant::Mutator::Node
  - Mutant::Meta::Example::Verification
  - Mutant::Parallel::Master
  max_methods: 10
TooManyStatements:
  enabled: true
  exclude:
  - Mutant::Isolation::Fork#self.call
  - Mutant::Reporter::CLI::Printer::EnvProgress#run
  - Mutant::Reporter::CLI::Printer::Config#run
  - Mutant::Zombifier::File#self.find
  - Mutant::CLI#add_environment_options
  - Mutant::CLI#add_debug_options
  - Mutant::Runner#run_driver
  max_statements: 7
UncommunicativeMethodName:
  enabled: true
  exclude:
  - Mutant::Mutation#sha1
  - Mutant::AST::Sexp#s
  reject:
  - !ruby/regexp /^[a-z]$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeModuleName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  accept: []
UncommunicativeParameterName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeVariableName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: ['force_utf32']
UnusedParameters:
  enabled: true
  exclude: []
UtilityFunction:
  enabled: true
  exclude:
  - Mutant::Actor::Env#new_mailbox
  - Mutant::AST::Sexp#s
  - Mutant::CLI#reporter
  - Mutant::Integration::Null#call
  - Mutant::Integration::Rspec#parse_example
  - Mutant::Meta::Example::Verification#format_mutation
  - Mutant::Reporter::CLI::Format::Progressive#new_buffer
  - Mutant::Reporter::CLI::Printer::StatusProgressive#object # False positive calls super
  - Mutant::Integration::Rspec#parse_expression # intentional, private
  max_helper_calls: 0
